### ISSUE TITLE
Consider changing the extension of your .txt files to .md

### ISSUE THREAD

**Issue by dbohdan** [saniv/text#1]
Hi! I found your collection of PL criticism by chance. What you've written in `text/criticism` is interesting reading but it looks bad on GitHub because GitHub won't wrap long lines in plain text files. Since most of the files in question are already formatted as lists changing the extension to `.md` would make them a lot more readable. Compare [-1-](https://github.com/saniv/text/blob/master/criticism/c.txt) (unreadable), [-2-](https://raw.githubusercontent.com/saniv/text/master/criticism/c.txt) (better) and [-3-](https://gist.github.com/dbohdan/0544c56cfd51b4a8f8ee) (the best).

**Comment by saniv** [comment]
Hi, dbohdan!

I've too little time, but you can always fork it change any way you like.

**Comment by dbohdan** [comment]
All right. I've forked the repo and converted the notes in `criticism/` to what I think is reasonable quality Markdown (I say "reasonable" rather than "good" because not every bit of code is marked as such). I've made a pull request (#2) to merge those changes back into your repo.
