### ISSUE TITLE
|

### ISSUE THREAD

**Issue by bl00mber** [saniv/text#6]

**Comment by Mikotochan** [comment]
@saniv What happened, what is this censorship?

**Comment by saniv** [comment]
These photos were copyrighted and I don't have permission to share them, so I removed them out of respect for intellectual property. I've also took down glorious-russia - a repository with funny photos and motivational posters about Russia.

**Comment by Mikotochan** [comment]
Why would you ever respect intellectual property? I am truly disgusted.

**Comment by saniv** [comment]
I'm also reporting other people for copyright infringement: https://github.com/saniv/free-game-art/blob/master/foss-copyright-infringement-records.md
